### ISSUE TITLE
Bhai check my code for 1st question of leetcode biweekly contest 74

### ISSUE THREAD

**Issue by madm234** [adityagi02/LeetCode-Weekly-Solutions#1]
//bhai iska answer galat kyon aara hai .Can't get it. Chote array ke liye sahi aara hai but badi array ke liye galat ho jara.
//(Divide Array Into Equal Pairs)

```
class Solution {
    public boolean divideArray(int[] nums) {
        int fin =0;
        
           for(int i=0;i<nums.length;i++)
           {
              fin ^=nums[i]; 
           }
        
        if(fin==0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
}
```

**Comment by adityagi02** [comment]
Ye galat tarika hai,

First check ki nums 2 se divisible hai kya.

Then isme problem hai ki using this operator between two operands ka result 3rd operand ke saath operate hokar solution wrong kar sakta hai, yaha shayad yahi hua hai.

**Comment by madm234** [comment]
1. Question mein de rakha hai ki array even hai to 2 se divisible krne ki zaroorat nhi pdegi.
`You are given an integer array nums consisting of 2 * n integers.`

2. teesre operand pe farak nhi pdega .Let me explain:
    `2^3^4^9^6^3^2^4^9`
    `(2^2)^(3^3)^(4^4)^(9^9)^6`
    `gives out 0^6 = 6`





**MERE 2 CASE FAIL HORE HAIN BAS , AUR PTA NAHI KYON!!!!**
